const assert = require('assert');
const fs = require('fs');
const path = require('path');
const html = fs.readFileSync(path.join(__dirname, '../dist/academy.html'), 'utf8');
const app = fs.readFileSync(path.join(__dirname, '../dist/app.js'), 'utf8');
const css = fs.readFileSync(path.join(__dirname, '../dist/styles.css'), 'utf8');

assert.ok(html.includes('terminal-practice-mission'), 'guided mission exists inside the Terminal');
assert.ok(html.includes('terminal-practice-validate'), 'mission exposes a validation action');
assert.ok(html.includes('Repère une zone, sans chercher à prédire.'), 'mission stays educational and non-predictive');
assert.ok(html.includes('id="terminal-zoom-in"') && html.includes('id="terminal-zoom-out"'), 'chart zoom controls live in the compact floating toolbar');
assert.ok(html.includes('value="4H"') && html.includes('value="1H"'), 'compact timeframe selector includes intraday choices');
assert.ok(html.includes('aria-pressed="true"'), 'drawing toolbar exposes accessible pressed state');
assert.ok(html.includes('id="terminal-undo-drawing"') && html.includes('id="terminal-clear-drawings"'), 'learner can undo or clear chart annotations');
assert.ok(app.includes("svg.addEventListener('pointerup'"), 'drawings are committed as direct pointer gestures');
assert.ok(app.includes("terminalInteraction.draft = { type: terminalInteraction.tool, x1: point.x"), 'annotation previews begin on pointer down');
assert.ok(app.includes('`translate(0 ${labelY})`'), 'crosshair value-axis label tracks its actual vertical position');
assert.ok(app.includes("const zones = state.drawings.filter(drawing => drawing.type === 'zone')"), 'validation reads the learner zone annotation');
assert.ok(app.includes("const status = valid ? 'validated' : 'retry'"), 'practice creates an explicit local status');
assert.ok(app.includes("proof: { id: 'm02-zone-identification'"), 'incorrect and successful practice share the typed proof contract');
assert.ok(app.includes('Preuve conservée localement'), 'feedback never claims market performance');
assert.ok(app.includes('completedAt: new Date().toISOString()'), 'successful proof has a local timestamp');
assert.ok(css.includes('.terminal-practice-mission'), 'mission has dedicated responsive styling');
assert.ok(css.includes('#060d17'), 'chart canvas uses the Deep Navy brand surface');
assert.ok(css.includes('.analysis-terminal-tools'), 'pro floating chart toolbar has dedicated styling');
console.log('RESULT: Practice Terminal guided mission contract passed');
